"""
ProjectIdeaAgent — Generates personalized FYP ideas based on student profile and constraints.

Generates exactly 3 ideas with deterministic scoring (no LLM invention).
Scores are calculated based on input parameters, not generated by Ollama.
"""

import logging
from typing import Optional
from pydantic import BaseModel

logger = logging.getLogger("fypilot-agent")

# ── Pydantic models for request/response ──────────────────────────────────


class StudentProfile(BaseModel):
    """Student profile for idea generation."""
    studentSkills: list[str]  # e.g., ["Python", "React", "SQL"]
    skillRatings: dict[str, int]  # e.g., {"Python": 4, "React": 3, "SQL": 2}
    major: str  # e.g., "Computer Science"
    experienceLevel: int  # 0-5 (0=beginner, 5=expert)
    preferredDomain: str  # e.g., "Web Development", "Mobile", "AI/ML"
    targetDifficulty: int  # 1-5 (1=easy, 5=very hard)
    availableHoursPerWeek: int  # e.g., 15
    teamSize: int  # e.g., 2 or 3
    projectGoals: list[str]  # e.g., ["Learn new tech", "Build portfolio"]
    lebaneseMarketRelevance: bool  # True/False


class ProjectIdea(BaseModel):
    """A single project idea with 18 required fields."""
    title: str
    problemStatement: str
    targetUsers: str
    whyUseful: str
    lebaneseMarketRelevance: str
    requiredTechnologies: list[str]
    requiredSkills: list[str]
    missingSkills: list[str]
    difficultyLevel: int  # 1-5
    innovationScore: float  # 0-100
    feasibilityScore: float  # 0-100
    marketDemandScore: float  # 0-100
    expectedDurationWeeks: int
    supervisorCategory: str
    datasetNeeded: list[str]
    finalDeliverables: list[str]
    domain: str
    lebaneseSector: str


class IdeaGenerationRequest(BaseModel):
    """Request to generate project ideas."""
    profile: StudentProfile


class IdeaGenerationResponse(BaseModel):
    """Response with 3 generated ideas."""
    ideas: list[ProjectIdea]
    generatedAt: str


# ── Scoring Functions (Deterministic) ─────────────────────────────────────


def calculate_innovation_score(
    experience_level: int,
    domain: str,
    difficulty: int,
    student_skills_count: int,
) -> float:
    """
    Calculate innovation score deterministically.
    
    Factors:
    - Experience level (higher = more innovation potential)
    - Domain trendiness (AI/ML scores higher)
    - Target difficulty (higher difficulty = more innovation)
    - Skill diversity (more skills = more innovation)
    """
    base_score = 40.0
    
    # Experience boost (0-15 points)
    experience_boost = experience_level * 3
    
    # Domain boost (0-20 points)
    domain_boosts = {
        "AI/ML": 20,
        "Machine Learning": 20,
        "Deep Learning": 20,
        "Web Development": 10,
        "Mobile Development": 15,
        "IoT": 18,
        "Blockchain": 18,
        "Cloud": 15,
    }
    domain_boost = domain_boosts.get(domain, 8)
    
    # Difficulty boost (0-15 points)
    difficulty_boost = difficulty * 3
    
    # Skill diversity boost (0-10 points)
    skill_boost = min(student_skills_count * 2, 10)
    
    total = base_score + experience_boost + domain_boost + difficulty_boost + skill_boost
    return min(total, 100.0)


def calculate_feasibility_score(
    student_skills: list[str],
    skill_ratings: dict[str, int],
    required_skills: list[str],
    available_hours: int,
    difficulty: int,
) -> float:
    """
    Calculate feasibility score deterministically.
    
    Factors:
    - Skill match with required skills
    - Available hours (more hours = more feasible)
    - Difficulty level (higher difficulty = less feasible)
    """
    base_score = 50.0
    
    # Skill match (0-30 points)
    if required_skills:
        matched_skills = [
            skill for skill in required_skills if skill in student_skills
        ]
        skill_match_ratio = len(matched_skills) / len(required_skills)
        
        # Average rating of matched skills
        matched_ratings = [
            skill_ratings.get(skill, 2) for skill in matched_skills
        ]
        avg_rating = (
            sum(matched_ratings) / len(matched_ratings) if matched_ratings else 1
        )
        skill_boost = skill_match_ratio * 30 * (avg_rating / 5)
    else:
        skill_boost = 0
    
    # Hours availability boost (0-20 points)
    hours_boost = min(available_hours / 2, 20)
    
    # Difficulty penalty (0-20 points deducted)
    difficulty_penalty = difficulty * 4
    
    total = base_score + skill_boost + hours_boost - difficulty_penalty
    return max(min(total, 100.0), 10.0)


def calculate_market_demand_score(
    lebanese_relevance: bool,
    difficulty: int,
    domain: str,
    sector: str,
) -> float:
    """
    Calculate market demand score deterministically.
    
    Factors:
    - Lebanese market relevance (boolean boost)
    - Domain market trends
    - Sector viability
    """
    base_score = 50.0
    
    # Lebanese market boost (0-25 points)
    lebanese_boost = 25.0 if lebanese_relevance else 5.0
    
    # Domain market demand (0-15 points)
    domain_demand = {
        "AI/ML": 15,
        "Machine Learning": 15,
        "Web Development": 12,
        "Mobile Development": 14,
        "IoT": 13,
        "Blockchain": 10,
        "Cloud": 13,
        "E-Commerce": 14,
    }
    domain_boost = domain_demand.get(domain, 8)
    
    # Difficulty alignment (mid-range difficulty = higher demand)
    # 1-2: too simple (low demand), 3: peak, 4-5: niche
    if difficulty <= 2:
        difficulty_boost = 3
    elif difficulty == 3:
        difficulty_boost = 10
    elif difficulty <= 4:
        difficulty_boost = 6
    else:
        difficulty_boost = 2
    
    # Sector viability (if Lebanese sector provided)
    sector_boost = 3 if sector else 0
    
    total = base_score + lebanese_boost + domain_boost + difficulty_boost + sector_boost
    return min(total, 100.0)


# ── ProjectIdeaAgent ───────────────────────────────────────────────────────


class ProjectIdeaAgent:
    """
    Generates 3 personalized FYP ideas based on student profile.
    
    All scores are deterministic and based on input parameters.
    Ollama (if available) is used only for optional text enhancement.
    """

    def __init__(self):
        """Initialize the agent."""
        self.logger = logging.getLogger("fypilot-agent")

    def generate_ideas(self, profile: StudentProfile) -> list[ProjectIdea]:
        """
        Generate exactly 3 personalized project ideas.
        
        Args:
            profile: StudentProfile with skills, major, goals, etc.
            
        Returns:
            List of 3 ProjectIdea objects with all 18 required fields.
        """
        ideas = []
        
        # Generate 3 ideas with different focus areas
        idea_templates = [
            self._generate_idea_1(profile),
            self._generate_idea_2(profile),
            self._generate_idea_3(profile),
        ]
        
        for idea_data in idea_templates:
            idea = self._build_idea(profile, idea_data)
            ideas.append(idea)
        
        return ideas

    def _generate_idea_1(self, profile: StudentProfile) -> dict:
        """Generate idea 1: Leverage primary skill + preferred domain."""
        primary_skill = (
            profile.studentSkills[0]
            if profile.studentSkills
            else "General Software"
        )
        
        return {
            "title": f"{profile.preferredDomain} Solution Using {primary_skill}",
            "domain": profile.preferredDomain,
            "sector": "Technology Services",
            "focus": "skill_leveraging",
        }

    def _generate_idea_2(self, profile: StudentProfile) -> dict:
        """Generate idea 2: Market-driven approach for Lebanese context."""
        return {
            "title": f"Lebanese Market {profile.preferredDomain} Solution",
            "domain": profile.preferredDomain,
            "sector": "E-Commerce / Business Services",
            "focus": "market_driven",
        }

    def _generate_idea_3(self, profile: StudentProfile) -> dict:
        """Generate idea 3: Innovation + skill learning."""
        return {
            "title": f"Innovative {profile.preferredDomain} Tool",
            "domain": profile.preferredDomain,
            "sector": "Technology Innovation",
            "focus": "innovation_learning",
        }

    def _build_idea(self, profile: StudentProfile, template: dict) -> ProjectIdea:
        """Build complete ProjectIdea from template."""
        domain = template["domain"]
        sector = template["sector"]
        focus = template["focus"]
        
        # Map primary required skills based on domain
        required_skills_map = {
            "Web Development": ["HTML/CSS", "JavaScript", "Backend Framework"],
            "Mobile Development": ["Mobile Framework", "UI Design", "Database"],
            "AI/ML": ["Python", "Machine Learning", "Data Processing"],
            "Blockchain": ["Solidity", "Web3", "Smart Contracts"],
            "IoT": ["Embedded Systems", "Microcontrollers", "Networking"],
            "Cloud": ["Cloud Services", "DevOps", "Networking"],
            "E-Commerce": ["Web Development", "Payment Systems", "Database"],
        }
        
        required_skills = required_skills_map.get(
            domain, ["General Software", "Problem Solving"]
        )
        
        # Find missing skills
        missing_skills = [s for s in required_skills if s not in profile.studentSkills]
        
        # Calculate scores
        innovation_score = calculate_innovation_score(
            profile.experienceLevel,
            domain,
            profile.targetDifficulty,
            len(profile.studentSkills),
        )
        
        feasibility_score = calculate_feasibility_score(
            profile.studentSkills,
            profile.skillRatings,
            required_skills,
            profile.availableHoursPerWeek,
            profile.targetDifficulty,
        )
        
        market_demand_score = calculate_market_demand_score(
            profile.lebaneseMarketRelevance,
            profile.targetDifficulty,
            domain,
            sector,
        )
        
        # Estimate duration based on difficulty and hours
        base_weeks = 12
        difficulty_adjustment = (profile.targetDifficulty - 2) * 2
        hours_adjustment = (20 - profile.availableHoursPerWeek) // 2
        expected_duration = max(
            4, base_weeks + difficulty_adjustment + hours_adjustment
        )
        
        # Select supervisor category based on domain
        supervisor_categories = {
            "Web Development": "Web & Cloud Computing",
            "Mobile Development": "Mobile & Cross-Platform",
            "AI/ML": "Data Science & AI",
            "Blockchain": "Distributed Systems",
            "IoT": "Embedded Systems & IoT",
            "Cloud": "Web & Cloud Computing",
            "E-Commerce": "Web & Business Systems",
        }
        supervisor_category = supervisor_categories.get(domain, "General Software")
        
        # Build Lebanese market relevance text
        lebanese_relevance_text = (
            "High relevance to Lebanese market — targets local business needs"
            if profile.lebaneseMarketRelevance
            else "Potential for Lebanese market adaptation with additional features"
        )
        
        return ProjectIdea(
            title=template["title"],
            problemStatement=self._generate_problem_statement(domain, focus),
            targetUsers=self._generate_target_users(domain, sector),
            whyUseful=self._generate_why_useful(domain, focus),
            lebaneseMarketRelevance=lebanese_relevance_text,
            requiredTechnologies=self._get_technologies(domain),
            requiredSkills=required_skills,
            missingSkills=missing_skills,
            difficultyLevel=profile.targetDifficulty,
            innovationScore=round(innovation_score, 1),
            feasibilityScore=round(feasibility_score, 1),
            marketDemandScore=round(market_demand_score, 1),
            expectedDurationWeeks=int(expected_duration),
            supervisorCategory=supervisor_category,
            datasetNeeded=self._get_datasets_needed(domain),
            finalDeliverables=self._get_deliverables(domain),
            domain=domain,
            lebaneseSector=sector,
        )

    def _generate_problem_statement(self, domain: str, focus: str) -> str:
        """Generate a problem statement based on domain and focus."""
        problems = {
            "Web Development": {
                "skill_leveraging": "Lack of efficient web solutions for small Lebanese businesses",
                "market_driven": "Businesses struggle with outdated web presence and digital transformation",
                "innovation_learning": "Gap in modern web technologies for Lebanese market applications",
            },
            "Mobile Development": {
                "skill_leveraging": "Mobile-first solutions are needed for Lebanese consumer market",
                "market_driven": "Businesses lack mobile-first customer engagement tools",
                "innovation_learning": "Innovation gap in cross-platform mobile development",
            },
            "AI/ML": {
                "skill_leveraging": "AI solutions can optimize Lebanese business processes",
                "market_driven": "Data-driven decision making is absent in Lebanese SMEs",
                "innovation_learning": "Emerging AI applications relevant to local industries",
            },
        }
        
        domain_problems = problems.get(domain, {})
        return domain_problems.get(
            focus,
            f"Addressing inefficiencies in {domain} for Lebanese context",
        )

    def _generate_target_users(self, domain: str, sector: str) -> str:
        """Generate target users description."""
        user_map = {
            "Technology Services": "Businesses seeking digital transformation",
            "E-Commerce / Business Services": "SMEs and online retailers in Lebanon",
            "Technology Innovation": "Tech-forward companies and startups",
        }
        return user_map.get(sector, f"Users in {sector}")

    def _generate_why_useful(self, domain: str, focus: str) -> str:
        """Generate why this idea is useful."""
        reasons = {
            "skill_leveraging": "Leverages your existing expertise while building portfolio",
            "market_driven": "Directly addresses Lebanese market gaps and business needs",
            "innovation_learning": "Combines innovation with skill development in emerging areas",
        }
        return reasons.get(focus, "Provides practical value and learning opportunities")

    def _get_technologies(self, domain: str) -> list[str]:
        """Get required technologies for domain."""
        tech_map = {
            "Web Development": ["HTML5", "CSS3", "JavaScript", "Backend Framework", "PostgreSQL"],
            "Mobile Development": ["React Native / Flutter", "Mobile UI Framework", "API Integration"],
            "AI/ML": ["Python", "TensorFlow / PyTorch", "Pandas", "Scikit-learn"],
            "Blockchain": ["Ethereum", "Solidity", "Web3.js", "Smart Contracts"],
            "IoT": ["Arduino / Raspberry Pi", "Embedded C", "MQTT", "IoT Platform"],
            "Cloud": ["AWS / Azure / GCP", "Docker", "Kubernetes", "CI/CD"],
        }
        return tech_map.get(domain, ["General Software Development Tools"])

    def _get_datasets_needed(self, domain: str) -> list[str]:
        """Get datasets needed for the project."""
        datasets_map = {
            "AI/ML": ["Training dataset (1000+ samples)", "Validation dataset"],
            "Web Development": ["User behavior data", "Market statistics (optional)"],
            "Mobile Development": ["User testing data", "Performance metrics"],
            "Blockchain": ["Transaction simulation data"],
            "E-Commerce": ["Product catalog", "Customer behavior data"],
        }
        return datasets_map.get(domain, ["Project-specific test data"])

    def _get_deliverables(self, domain: str) -> list[str]:
        """Get final deliverables."""
        deliverables_map = {
            "Web Development": [
                "Fully functional web application",
                "API documentation",
                "User manual",
                "Code repository with documentation",
            ],
            "Mobile Development": [
                "Mobile application (iOS/Android)",
                "User testing report",
                "Installation guide",
                "Performance benchmarks",
            ],
            "AI/ML": [
                "Trained machine learning model",
                "Model evaluation report",
                "Inference pipeline",
                "Documentation and usage guide",
            ],
            "Blockchain": [
                "Smart contract code",
                "DApp interface",
                "Test suite",
                "Deployment documentation",
            ],
        }
        return deliverables_map.get(
            domain,
            ["Source code", "Documentation", "Testing report", "Demo"],
        )
