using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FYPilot.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddFeedbackMessages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "FeedbackMessages" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "EvaluationId" integer NOT NULL,
                    "SenderUserId" integer NOT NULL,
                    "MessageText" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_FeedbackMessages" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_FeedbackMessages_supervisor_evaluations_EvaluationId"
                        FOREIGN KEY ("EvaluationId")
                        REFERENCES supervisor_evaluations (id)
                        ON DELETE CASCADE
                );
            """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_FeedbackMessages_EvaluationId"
                ON "FeedbackMessages" ("EvaluationId");
            """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "FeedbackMessages";
            """);
        }
    }
}