// <auto-generated />
using System;
using FYPilot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FYPilot.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612223740_AddFeedbackMessages")]
    partial class AddFeedbackMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FYPilot.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("activity");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_skills");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("challenges");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdeaId")
                        .HasColumnType("integer")
                        .HasColumnName("idea_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("company_profiles");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.FeasibilityReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DifficultyMatchScore")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_match_score");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<int>("FinalFeasibilityScore")
                        .HasColumnType("integer")
                        .HasColumnName("final_feasibility_score");

                    b.Property<int>("IdeaId")
                        .HasColumnType("integer")
                        .HasColumnName("idea_id");

                    b.Property<int>("InnovationScore")
                        .HasColumnType("integer")
                        .HasColumnName("innovation_score");

                    b.Property<int>("MarketUsefulnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("market_usefulness_score");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("RisksJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risks_json");

                    b.Property<int>("SkillMatchScore")
                        .HasColumnType("integer")
                        .HasColumnName("skill_match_score");

                    b.Property<int>("TimelineFitScore")
                        .HasColumnType("integer")
                        .HasColumnName("timeline_fit_score");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId")
                        .IsUnique();

                    b.ToTable("feasibility_reports");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("integer")
                        .HasColumnName("supervisor_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("feedback");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.FeedbackMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("integer");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("FeedbackMessages");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.MarketNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("business_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DemandScore")
                        .HasColumnType("integer")
                        .HasColumnName("demand_score");

                    b.Property<string>("PossibleSolution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("possible_solution");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.HasKey("Id");

                    b.ToTable("market_needs");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("completion_percentage");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DueDate")
                        .HasColumnType("text")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("milestones");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.PreviousProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("technologies");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("university");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("previous_projects");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EndDate")
                        .HasColumnType("text")
                        .HasColumnName("end_date");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<string>("StartDate")
                        .HasColumnType("text")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("integer")
                        .HasColumnName("supervisor_id");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("technologies");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ProjectDocumentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiTechnicalReportJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatabaseDesignJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiagramDescriptionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EdgeCasesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FunctionalRequirementsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NonFunctionalRequirementsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectIdeaId")
                        .HasColumnType("integer");

                    b.Property<string>("SupervisorComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UiDesignJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UseCasesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("project_documentations", (string)null);
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ProjectIdea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetNeeded")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataset_needed");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<int>("ExpectedDurationWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("expected_duration_weeks");

                    b.Property<int>("FeasibilityScore")
                        .HasColumnType("integer")
                        .HasColumnName("feasibility_score");

                    b.Property<string>("FinalDeliverables")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("final_deliverables");

                    b.Property<int>("InnovationScore")
                        .HasColumnType("integer")
                        .HasColumnName("innovation_score");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.Property<string>("LebaneseMarketRelevance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lebanese_market_relevance");

                    b.Property<string>("LebanesesSector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lebanese_sector");

                    b.Property<int>("MarketDemandScore")
                        .HasColumnType("integer")
                        .HasColumnName("market_demand_score");

                    b.Property<string>("MissingSkills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("missing_skills");

                    b.Property<string>("ProblemStatement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem_statement");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_skills");

                    b.Property<string>("RequiredTechnologies")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_technologies");

                    b.Property<string>("SupervisorCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supervisor_category");

                    b.Property<string>("TargetUsers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_users");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("WhyUseful")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("why_useful");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("project_ideas");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ProjectRoadmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdeaId")
                        .HasColumnType("integer")
                        .HasColumnName("idea_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.ToTable("project_roadmaps");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DueDate")
                        .HasColumnType("text")
                        .HasColumnName("due_date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.RoadmapPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dependencies")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dependencies");

                    b.Property<int>("EstimatedWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_weeks");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_output");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<int>("PhaseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("phase_number");

                    b.Property<string>("Risks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risks");

                    b.Property<int>("RoadmapId")
                        .HasColumnType("integer")
                        .HasColumnName("roadmap_id");

                    b.Property<string>("SuccessCriteria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("success_criteria");

                    b.Property<string>("TasksJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tasks_json");

                    b.Property<string>("ToolsNeeded")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tools_needed");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.ToTable("roadmap_phases");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableHoursPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("available_hours_per_week");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("experience_level");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interests");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("major");

                    b.Property<string>("PreferredDomain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_domain");

                    b.Property<string>("PreferredStack")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_stack");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_path");

                    b.Property<string>("ProjectGoals")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_goals");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skills");

                    b.Property<string>("TargetDifficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_difficulty");

                    b.Property<int>("TeamMembers")
                        .HasColumnType("integer")
                        .HasColumnName("team_members");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("university");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("student_profiles");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.StudentSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("student_skills");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.SupervisorEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdeaId")
                        .HasColumnType("integer")
                        .HasColumnName("idea_id");

                    b.Property<string>("ImprovementSuggestions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("improvement_suggestions");

                    b.Property<int>("OriginalityScore")
                        .HasColumnType("integer")
                        .HasColumnName("originality_score");

                    b.Property<int>("SimilarityScore")
                        .HasColumnType("integer")
                        .HasColumnName("similarity_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("integer")
                        .HasColumnName("supervisor_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("supervisor_evaluations");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.SupervisorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("supervisor_profiles");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("student")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Activity", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.CompanyProfile", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "User")
                        .WithOne("CompanyProfile")
                        .HasForeignKey("FYPilot.Domain.Entities.CompanyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.FeasibilityReport", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.ProjectIdea", "Idea")
                        .WithOne("FeasibilityReport")
                        .HasForeignKey("FYPilot.Domain.Entities.FeasibilityReport", "IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.Project", "Project")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYPilot.Domain.Entities.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.FeedbackMessage", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.SupervisorEvaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Milestone", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Project", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "Student")
                        .WithMany("Projects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYPilot.Domain.Entities.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ProjectIdea", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ProjectRoadmap", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.ProjectIdea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.RoadmapPhase", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.ProjectRoadmap", "Roadmap")
                        .WithMany("Phases")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("FYPilot.Domain.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.StudentSkill", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.SupervisorEvaluation", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.ProjectIdea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYPilot.Domain.Entities.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.SupervisorProfile", b =>
                {
                    b.HasOne("FYPilot.Domain.Entities.User", "User")
                        .WithOne("SupervisorProfile")
                        .HasForeignKey("FYPilot.Domain.Entities.SupervisorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.Project", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Milestones");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ProjectIdea", b =>
                {
                    b.Navigation("FeasibilityReport");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.ProjectRoadmap", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("FYPilot.Domain.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CompanyProfile");

                    b.Navigation("Projects");

                    b.Navigation("StudentProfile");

                    b.Navigation("SupervisorProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
