using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FYPilot.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddGoogleCalendarIntegration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Keep the existing meetings table.
            // Rename the old reminder column when it exists.
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS
                    (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'meetings'
                          AND column_name = 'reminder_12h_sent_at'
                    )
                    AND NOT EXISTS
                    (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'meetings'
                          AND column_name = 'reminder_12_hours_sent_at'
                    )
                    THEN
                        ALTER TABLE public.meetings
                        RENAME COLUMN reminder_12h_sent_at
                        TO reminder_12_hours_sent_at;
                    END IF;
                END
                $$;
                """);

            // If neither reminder-column name existed, create the new one.
            migrationBuilder.Sql(
                """
                ALTER TABLE IF EXISTS public.meetings
                ADD COLUMN IF NOT EXISTS reminder_12_hours_sent_at
                    timestamp with time zone NULL;
                """);

            // 2. Add only the Google Calendar fields to the existing meetings table.
            migrationBuilder.Sql(
                """
                ALTER TABLE IF EXISTS public.meetings
                ADD COLUMN IF NOT EXISTS google_calendar_event_id text NULL;

                ALTER TABLE IF EXISTS public.meetings
                ADD COLUMN IF NOT EXISTS google_calendar_event_link text NULL;

                ALTER TABLE IF EXISTS public.meetings
                ADD COLUMN IF NOT EXISTS google_meet_link text NULL;

                ALTER TABLE IF EXISTS public.meetings
                ADD COLUMN IF NOT EXISTS google_sync_status text NULL;

                ALTER TABLE IF EXISTS public.meetings
                ADD COLUMN IF NOT EXISTS last_google_sync_at
                    timestamp with time zone NULL;
                """);

            // 3. Create the token table expected by the current entity mapping.
            // IF NOT EXISTS makes this safe when the table was created manually.
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public.google_calendar_tokens
                (
                    id integer
                        GENERATED BY DEFAULT AS IDENTITY
                        PRIMARY KEY,

                    supervisor_id integer NOT NULL,

                    access_token text NOT NULL,

                    refresh_token text NOT NULL,

                    expiration timestamp with time zone NOT NULL,

                    created_at timestamp with time zone NOT NULL,

                    updated_at timestamp with time zone NOT NULL,

                    CONSTRAINT
                        "FK_google_calendar_tokens_users_supervisor_id"
                    FOREIGN KEY (supervisor_id)
                    REFERENCES public.users (id)
                    ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS
                    "IX_google_calendar_tokens_supervisor_id"
                ON public.google_calendar_tokens (supervisor_id);
                """);

            // 4. Preserve an existing Google connection when the older
            // PascalCase table is present. The old table is left untouched
            // as a backup; its rows are copied only when the supervisor does
            // not already have a row in the new table.
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF to_regclass('public."GoogleCalendarTokens"') IS NOT NULL
                    THEN
                        EXECUTE '
                            INSERT INTO public.google_calendar_tokens
                            (
                                supervisor_id,
                                access_token,
                                refresh_token,
                                expiration,
                                created_at,
                                updated_at
                            )
                            SELECT
                                old_token."SupervisorId",
                                old_token."AccessToken",
                                old_token."RefreshToken",
                                old_token."Expiration",
                                old_token."CreatedAt",
                                old_token."CreatedAt"
                            FROM public."GoogleCalendarTokens" AS old_token
                            WHERE NOT EXISTS
                            (
                                SELECT 1
                                FROM public.google_calendar_tokens AS new_token
                                WHERE new_token.supervisor_id =
                                      old_token."SupervisorId"
                            )';
                    END IF;
                END
                $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove only the Google Calendar structures introduced here.
            // Existing meetings and unrelated project tables are never dropped.
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS public.google_calendar_tokens;

                ALTER TABLE IF EXISTS public.meetings
                DROP COLUMN IF EXISTS google_calendar_event_id;

                ALTER TABLE IF EXISTS public.meetings
                DROP COLUMN IF EXISTS google_calendar_event_link;

                ALTER TABLE IF EXISTS public.meetings
                DROP COLUMN IF EXISTS google_meet_link;

                ALTER TABLE IF EXISTS public.meetings
                DROP COLUMN IF EXISTS google_sync_status;

                ALTER TABLE IF EXISTS public.meetings
                DROP COLUMN IF EXISTS last_google_sync_at;
                """);

            // Restore the old reminder-column name only when possible.
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS
                    (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'meetings'
                          AND column_name = 'reminder_12_hours_sent_at'
                    )
                    AND NOT EXISTS
                    (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'meetings'
                          AND column_name = 'reminder_12h_sent_at'
                    )
                    THEN
                        ALTER TABLE public.meetings
                        RENAME COLUMN reminder_12_hours_sent_at
                        TO reminder_12h_sent_at;
                    END IF;
                END
                $$;
                """);
        }
    }
}