using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FYPilot.Infrastructure.Migrations
{
    /// <summary>
    /// Repairs database/schema drift and adds the missing Supervisor Assignment,
    /// Mentor Chat Session, and Market Demand structures.
    ///
    /// This migration intentionally uses PostgreSQL IF NOT EXISTS checks because
    /// some development databases already contain Mentor Chat columns or tables
    /// that are missing from __EFMigrationsHistory.
    /// </summary>
    public partial class AddMissingSupervisorAndMentorTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // -----------------------------------------------------------------
            // 1. Google Calendar compatibility
            // -----------------------------------------------------------------
            migrationBuilder.Sql("""
                UPDATE meetings
                SET google_sync_status = ''
                WHERE google_sync_status IS NULL;

                ALTER TABLE meetings
                    ALTER COLUMN google_sync_status SET DEFAULT '';

                ALTER TABLE meetings
                    ALTER COLUMN google_sync_status SET NOT NULL;
                """);

            // -----------------------------------------------------------------
            // 2. Mentor Chat session column
            //    The column already exists in some local databases.
            // -----------------------------------------------------------------
            migrationBuilder.Sql("""
                ALTER TABLE chat_messages
                ADD COLUMN IF NOT EXISTS mentor_chat_session_id integer;
                """);

            // -----------------------------------------------------------------
            // 3. Main tables
            // -----------------------------------------------------------------
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS market_demand_analysis
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ProjectIdeaId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "DemandScore" integer NOT NULL,
                    "ConfidenceScore" integer NOT NULL,
                    "ProblemEvidenceScore" integer NOT NULL,
                    "MarketFitScore" integer NOT NULL,
                    "UniversityValueScore" integer NOT NULL,
                    "CompetitionOpportunityScore" integer NOT NULL,
                    "TechnologyMomentumScore" integer NOT NULL,
                    "MarketDemand" character varying(50) NOT NULL,
                    "TargetSector" character varying(300) NOT NULL,
                    "CountryContext" character varying(120) NOT NULL,
                    "Source" character varying(120) NOT NULL,
                    "Provider" character varying(120) NOT NULL,
                    "ModelUsed" character varying(200),
                    "SearchUsed" boolean NOT NULL,
                    "SearchProvider" character varying(200),
                    "GroundedInLiveData" boolean NOT NULL,
                    "ConfidenceLevel" character varying(30) NOT NULL,
                    "CloudError" text,
                    "ProblemEvidenceJson" text NOT NULL,
                    "LebaneseMarketFit" text NOT NULL,
                    "UniversityValue" text NOT NULL,
                    "RisksJson" text NOT NULL,
                    "Recommendation" text NOT NULL,
                    "NextStepsJson" text NOT NULL,
                    "ForecastStatus" character varying(80) NOT NULL,
                    "ForecastReady" boolean NOT NULL,
                    "ForecastReliable" boolean NOT NULL,
                    "ForecastModel" character varying(120),
                    "ForecastMae" numeric,
                    "NaiveForecastMae" numeric,
                    "ForecastPointsJson" text NOT NULL,
                    "ForecastWarning" text,
                    "ForecastGeneratedAt" timestamp with time zone,
                    "TrendDirection" character varying(30) NOT NULL,
                    "TrendStrength" character varying(30) NOT NULL,
                    "TrendSlopePerWeek" numeric,
                    "TrendTotalChange" numeric,
                    "TrendVolatility" numeric,
                    "TrendRSquared" numeric,
                    "TrendSummary" text,
                    "AnalyzedAt" timestamp with time zone NOT NULL,

                    CONSTRAINT "PK_market_demand_analysis"
                        PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS mentor_chat_sessions
                (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    user_id integer NOT NULL,
                    idea_id integer,
                    title character varying(120) NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    deleted_at timestamp with time zone,

                    CONSTRAINT "PK_mentor_chat_sessions"
                        PRIMARY KEY (id)
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS supervisor_assignments
                (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    student_id integer NOT NULL,
                    supervisor_id integer NOT NULL,
                    assigned_by_admin_id integer,
                    status text NOT NULL,
                    student_message text NOT NULL,
                    admin_note text NOT NULL,
                    requested_at timestamp with time zone NOT NULL,
                    approved_at timestamp with time zone,
                    rejected_at timestamp with time zone,
                    updated_at timestamp with time zone NOT NULL,

                    CONSTRAINT "PK_supervisor_assignments"
                        PRIMARY KEY (id)
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS market_demand_sources
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "MarketDemandAnalysisId" integer NOT NULL,
                    "Title" character varying(500) NOT NULL,
                    "Url" character varying(2000) NOT NULL,
                    "Publisher" character varying(250) NOT NULL,
                    "Relevance" text NOT NULL,
                    "RelevanceScore" integer NOT NULL,
                    "SourceType" character varying(100) NOT NULL,
                    "IsVerified" boolean NOT NULL,
                    "AccessedAt" timestamp with time zone NOT NULL,

                    CONSTRAINT "PK_market_demand_sources"
                        PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS market_demand_yearly_points
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "MarketDemandAnalysisId" integer NOT NULL,
                    "Year" integer NOT NULL,
                    "ProblemSignal" integer NOT NULL,
                    "AdoptionSignal" integer NOT NULL,
                    "JobDemandSignal" integer NOT NULL,
                    "TechnologyMomentumSignal" integer NOT NULL,
                    "DemandIndex" numeric(6,2) NOT NULL,
                    "ConfidenceScore" integer NOT NULL,
                    "EvidenceSummary" text NOT NULL,
                    "SourceUrlsJson" text NOT NULL,

                    CONSTRAINT "PK_market_demand_yearly_points"
                        PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS market_similar_solutions
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "MarketDemandAnalysisId" integer NOT NULL,
                    "Name" character varying(300) NOT NULL,
                    "Description" text NOT NULL,
                    "Similarity" character varying(30) NOT NULL,

                    CONSTRAINT "PK_market_similar_solutions"
                        PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS market_trend_signals
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "MarketDemandAnalysisId" integer NOT NULL,
                    "Topic" character varying(300) NOT NULL,
                    "Direction" character varying(30) NOT NULL,
                    "Evidence" text NOT NULL,
                    "SourceUrl" character varying(2000),

                    CONSTRAINT "PK_market_trend_signals"
                        PRIMARY KEY ("Id")
                );
                """);

            // -----------------------------------------------------------------
            // 4. Indexes
            // -----------------------------------------------------------------
            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_chat_messages_mentor_chat_session_id"
                    ON chat_messages (mentor_chat_session_id);

                CREATE INDEX IF NOT EXISTS "IX_market_demand_analysis_ProjectIdeaId"
                    ON market_demand_analysis ("ProjectIdeaId");

                CREATE INDEX IF NOT EXISTS "IX_market_demand_analysis_UserId_ProjectIdeaId_AnalyzedAt"
                    ON market_demand_analysis ("UserId", "ProjectIdeaId", "AnalyzedAt");

                CREATE INDEX IF NOT EXISTS "IX_market_demand_sources_MarketDemandAnalysisId"
                    ON market_demand_sources ("MarketDemandAnalysisId");

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_market_demand_yearly_points_MarketDemandAnalysisId_Year"
                    ON market_demand_yearly_points ("MarketDemandAnalysisId", "Year");

                CREATE INDEX IF NOT EXISTS "IX_market_similar_solutions_MarketDemandAnalysisId"
                    ON market_similar_solutions ("MarketDemandAnalysisId");

                CREATE INDEX IF NOT EXISTS "IX_market_trend_signals_MarketDemandAnalysisId"
                    ON market_trend_signals ("MarketDemandAnalysisId");

                CREATE INDEX IF NOT EXISTS "IX_mentor_chat_sessions_user_id"
                    ON mentor_chat_sessions (user_id);

                CREATE INDEX IF NOT EXISTS "IX_supervisor_assignments_assigned_by_admin_id"
                    ON supervisor_assignments (assigned_by_admin_id);

                CREATE INDEX IF NOT EXISTS "IX_supervisor_assignments_student_id"
                    ON supervisor_assignments (student_id);

                CREATE INDEX IF NOT EXISTS "IX_supervisor_assignments_supervisor_id"
                    ON supervisor_assignments (supervisor_id);
                """);

            // -----------------------------------------------------------------
            // 5. Foreign keys
            //    Each constraint is added only when that exact constraint name
            //    is not already present.
            // -----------------------------------------------------------------
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_market_demand_analysis_project_ideas_ProjectIdeaId'
                    )
                    THEN
                        ALTER TABLE market_demand_analysis
                        ADD CONSTRAINT
                            "FK_market_demand_analysis_project_ideas_ProjectIdeaId"
                        FOREIGN KEY ("ProjectIdeaId")
                        REFERENCES project_ideas (id)
                        ON DELETE CASCADE;
                    END IF;
                END
                $$;
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_mentor_chat_sessions_users_user_id'
                    )
                    THEN
                        ALTER TABLE mentor_chat_sessions
                        ADD CONSTRAINT
                            "FK_mentor_chat_sessions_users_user_id"
                        FOREIGN KEY (user_id)
                        REFERENCES users (id)
                        ON DELETE CASCADE;
                    END IF;
                END
                $$;
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_supervisor_assignments_users_assigned_by_admin_id'
                    )
                    THEN
                        ALTER TABLE supervisor_assignments
                        ADD CONSTRAINT
                            "FK_supervisor_assignments_users_assigned_by_admin_id"
                        FOREIGN KEY (assigned_by_admin_id)
                        REFERENCES users (id)
                        ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_supervisor_assignments_users_student_id'
                    )
                    THEN
                        ALTER TABLE supervisor_assignments
                        ADD CONSTRAINT
                            "FK_supervisor_assignments_users_student_id"
                        FOREIGN KEY (student_id)
                        REFERENCES users (id)
                        ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_supervisor_assignments_users_supervisor_id'
                    )
                    THEN
                        ALTER TABLE supervisor_assignments
                        ADD CONSTRAINT
                            "FK_supervisor_assignments_users_supervisor_id"
                        FOREIGN KEY (supervisor_id)
                        REFERENCES users (id)
                        ON DELETE CASCADE;
                    END IF;
                END
                $$;
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_market_demand_sources_market_demand_analysis'
                    )
                    THEN
                        ALTER TABLE market_demand_sources
                        ADD CONSTRAINT
                            "FK_market_demand_sources_market_demand_analysis"
                        FOREIGN KEY ("MarketDemandAnalysisId")
                        REFERENCES market_demand_analysis ("Id")
                        ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_market_demand_yearly_points_market_demand_analysis'
                    )
                    THEN
                        ALTER TABLE market_demand_yearly_points
                        ADD CONSTRAINT
                            "FK_market_demand_yearly_points_market_demand_analysis"
                        FOREIGN KEY ("MarketDemandAnalysisId")
                        REFERENCES market_demand_analysis ("Id")
                        ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_market_similar_solutions_market_demand_analysis'
                    )
                    THEN
                        ALTER TABLE market_similar_solutions
                        ADD CONSTRAINT
                            "FK_market_similar_solutions_market_demand_analysis"
                        FOREIGN KEY ("MarketDemandAnalysisId")
                        REFERENCES market_demand_analysis ("Id")
                        ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_market_trend_signals_market_demand_analysis'
                    )
                    THEN
                        ALTER TABLE market_trend_signals
                        ADD CONSTRAINT
                            "FK_market_trend_signals_market_demand_analysis"
                        FOREIGN KEY ("MarketDemandAnalysisId")
                        REFERENCES market_demand_analysis ("Id")
                        ON DELETE CASCADE;
                    END IF;
                END
                $$;
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname =
                            'FK_chat_messages_mentor_chat_sessions_mentor_chat_session_id'
                    )
                    THEN
                        ALTER TABLE chat_messages
                        ADD CONSTRAINT
                            "FK_chat_messages_mentor_chat_sessions_mentor_chat_session_id"
                        FOREIGN KEY (mentor_chat_session_id)
                        REFERENCES mentor_chat_sessions (id)
                        ON DELETE CASCADE;
                    END IF;
                END
                $$;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            throw new NotSupportedException(
                "Automatic rollback is disabled for this schema-repair migration " +
                "because some database objects existed before this migration was recorded. " +
                "Use a reviewed manual rollback script to avoid deleting existing data.");
        }
    }
}