"""
Tests for the RequirementsRegistry / two-phase section generation fix --
closes the live semantic-traceability defect (2026-08-07/08) where every
section prompt was built solely from the same static ProjectFacts context,
independently of one another: Requirements could define "FR-02 = Symptom
Description Submission" while testingSecurity, generated by a completely
separate LLM call with no visibility into that choice, independently
guessed "FR-02 = Login" for its own test cases. Every id referenced was
syntactically real, so structural validation never caught the drift.

Covers the 20 required proofs:
 1.  requirements registry preserves exact FR ids/titles
 2.  dependent prompt contains the immutable requirement registry
 3.  FR-02 cannot be redefined as Login when the registry says Symptom
     Submission
 4.  use case references the correct FR
 5.  module references the correct FR
 6.  entity references the correct FR
 7.  UI screen references the correct FR
 8.  API references the correct FR
 9.  test case references the correct FR
10.  matrix is built exclusively from child explicit references
11.  no positional mapping occurs
12.  empty references remain empty
13.  requirement reverse useCase/module ids are rebuilt from child links
14.  stale reverse references are removed
15.  duplicate references collapse
16.  a removed FR is never remapped to the first available FR
17.  medical fixture produces the documented minimum mappings
18.  the matrix never contains the specific corrupted links from the live
     defect report
19.  the full assembled candidate still passes structural validation
20.  no live provider is called anywhere in this file

No test in this file calls a live provider -- every DTO/registry/document
is constructed in-process; _assemble_documentation is called directly with
hand-built `sections` dicts instead of going through a real LLM call.

Run from services/FYPilot.AI:
    python -m pytest tests/test_se_documentation_requirements_registry.py
"""

from __future__ import annotations

import unittest

from app.agents.se_documentation.project_facts import build_project_facts
from app.agents.se_documentation.se_documentation_orchestrator import (
    EntityDto,
    EntityFieldDto,
    ModuleDto,
    RequirementDto,
    RequirementsRegistry,
    RequirementsRegistryEntry,
    SEDocumentationOrchestratorAgent,
    SEDocumentationRequest,
    TestCaseDto,
    UiScreenDto,
    UseCaseDto,
)
from app.review.registry import SEDocumentationCandidateSchema


def _agent() -> SEDocumentationOrchestratorAgent:
    return SEDocumentationOrchestratorAgent()


def _facts():
    return build_project_facts(SEDocumentationRequest())


# ---------------------------------------------------------------------------
# 1 -- registry preserves exact FR ids/titles
# ---------------------------------------------------------------------------

class RegistryContentTests(unittest.TestCase):
    def test_registry_preserves_exact_fr_ids_and_titles(self):
        frs = [
            RequirementDto(id="FR-01", title="Patient Account Registration and Login", description="", priority="High", source="s"),
            RequirementDto(id="FR-02", title="Symptom Description Submission", description="", priority="High", source="s"),
        ]
        nfrs = [
            RequirementDto(id="NFR-01", title="Triage Response Time", description="", priority="High", source="s"),
        ]

        registry = _agent()._build_requirements_registry(frs, nfrs)

        self.assertEqual(registry.ids, frozenset({"FR-01", "FR-02", "NFR-01"}))
        titles_by_id = {e.id: e.title for e in registry.entries}
        self.assertEqual(titles_by_id["FR-01"], "Patient Account Registration and Login")
        self.assertEqual(titles_by_id["FR-02"], "Symptom Description Submission")
        self.assertEqual(titles_by_id["NFR-01"], "Triage Response Time")


# ---------------------------------------------------------------------------
# 2, 3 -- dependent prompts carry the immutable registry; ids can't drift
# ---------------------------------------------------------------------------

class DependentPromptInjectionTests(unittest.TestCase):
    def test_dependent_prompts_contain_the_immutable_registry(self):
        facts = _facts()
        registry = RequirementsRegistry(entries=(
            RequirementsRegistryEntry(
                id="FR-02", title="Symptom Description Submission", description="",
                priority="High", sourceClassification="confirmed",
            ),
        ))

        prompts = _agent()._build_section_prompts("CONTEXT", facts, registry=registry)

        for key in ("useCases", "modulesArchitecture", "database", "uiApi", "testingSecurity"):
            prompt_text, _ = prompts[key]
            self.assertIn("FR-02 | Symptom Description Submission", prompt_text)
            self.assertIn("THESE IDS ARE IMMUTABLE", prompt_text)
            self.assertIn("Never redefine an id", prompt_text)

    def test_requirements_and_ai_report_prompts_never_receive_the_registry(self):
        facts = _facts()
        registry = RequirementsRegistry(entries=(
            RequirementsRegistryEntry(
                id="FR-02", title="Symptom Description Submission", description="",
                priority="High", sourceClassification="confirmed",
            ),
        ))

        prompts = _agent()._build_section_prompts("CONTEXT", facts, registry=registry)

        self.assertNotIn("THESE IDS ARE IMMUTABLE", prompts["requirements"][0])

    def test_fr02_cannot_be_redefined_as_login_when_registry_says_symptom_submission(self):
        """The registry's rendering is the ONLY place a dependent prompt
        learns what FR-02 means -- it appears exactly once, with the
        canonical title, so nothing in the prompt text itself offers a
        conflicting definition for the model to "choose" instead."""
        registry = RequirementsRegistry(entries=(
            RequirementsRegistryEntry(
                id="FR-02", title="Symptom Description Submission", description="",
                priority="High", sourceClassification="confirmed",
            ),
        ))

        rendered = registry.render_compact()

        self.assertEqual(rendered.count("FR-02"), 1)
        self.assertIn("FR-02 | Symptom Description Submission", rendered)
        self.assertNotIn("Login", rendered)


# ---------------------------------------------------------------------------
# 4-9 -- each dimension references the correct FR via its own explicit field
# ---------------------------------------------------------------------------

class PerDimensionReferenceTests(unittest.TestCase):
    def setUp(self):
        self.agent = _agent()
        self.fr02 = RequirementDto(id="FR-02", title="Symptom Description Submission", description="", priority="High", source="s")
        self.fr07 = RequirementDto(id="FR-07", title="Symptom Submission History", description="", priority="Medium", source="s")

    def _row_for(self, fr, **kwargs):
        defaults = dict(use_cases=[], modules=[], entities=[], tests=[], ui_screens=[], api_points=[])
        defaults.update(kwargs)
        rows = self.agent._build_traceability(
            [self.fr02, self.fr07], [],
            defaults["use_cases"], defaults["modules"], defaults["entities"],
            defaults["tests"], defaults["ui_screens"], defaults["api_points"],
        )
        return next(r for r in rows if r.requirementId == fr.id)

    def test_use_case_references_correct_fr(self):
        uc = UseCaseDto(id="UC-03", title="Submit Symptoms", actor="Patient", goal="", relatedRequirements=["FR-02"])
        row = self._row_for(self.fr02, use_cases=[uc])
        self.assertEqual(row.useCaseIds, ["UC-03"])

    def test_module_references_correct_fr(self):
        mod = ModuleDto(id="MOD-02", name="SymptomIntakeModule", responsibility="", relatedRequirements=["FR-02"])
        row = self._row_for(self.fr02, modules=[mod])
        self.assertEqual(row.moduleIds, ["MOD-02"])

    def test_entity_references_correct_fr(self):
        ent = EntityDto(entityId="ENT-02", name="TriageSession", purpose="", relatedRequirementIds=["FR-02"])
        row = self._row_for(self.fr02, entities=[ent])
        self.assertEqual(row.entityIds, ["ENT-02"])

    def test_ui_screen_references_correct_fr(self):
        screen = UiScreenDto(screenId="UI-02", name="Symptom Entry", relatedRequirements=["FR-02"])
        row = self._row_for(self.fr02, ui_screens=[screen])
        self.assertEqual(row.screenIds, ["UI-02"])

    def test_api_references_correct_fr(self):
        from app.agents.se_documentation.se_documentation_orchestrator import ApiPointDto
        api = ApiPointDto(
            apiId="API-01", name="Triage API", method="POST", endpoint="/triage",
            purpose="", requestSummary="", responseSummary="", relatedRequirements=["FR-02"],
        )
        row = self._row_for(self.fr02, api_points=[api])
        self.assertEqual(row.apiIds, ["API-01"])

    def test_test_case_references_correct_fr(self):
        test = TestCaseDto(id="TC-05", title="Symptom submission positive", type="Integration", expectedResult="Saved", relatedRequirements=["FR-02"])
        row = self._row_for(self.fr02, tests=[test])
        self.assertEqual(row.testCaseIds, ["TC-05"])


# ---------------------------------------------------------------------------
# 10, 11 -- exclusively from explicit references, never positional
# ---------------------------------------------------------------------------

class NoPositionalMappingTests(unittest.TestCase):
    def test_matrix_never_links_by_list_position_or_matching_number(self):
        """FR-02 is the SECOND fr; UC-02 is the SECOND use case -- if the
        builder ever fell back to positional/index matching, FR-02 would
        pick up UC-02 despite UC-02 declaring a completely different FR."""
        fr01 = RequirementDto(id="FR-01", title="Login", description="", priority="High", source="s")
        fr02 = RequirementDto(id="FR-02", title="Symptom Submission", description="", priority="High", source="s")
        uc01 = UseCaseDto(id="UC-01", title="Login", actor="Patient", goal="", relatedRequirements=["FR-01"])
        uc02 = UseCaseDto(id="UC-02", title="Logout", actor="Patient", goal="", relatedRequirements=["FR-01"])  # NOT FR-02, despite matching position

        rows = _agent()._build_traceability([fr01, fr02], [], [uc01, uc02], [], [], [], [], [])

        fr02_row = next(r for r in rows if r.requirementId == "FR-02")
        self.assertEqual(fr02_row.useCaseIds, [])
        self.assertNotIn("UC-02", fr02_row.useCaseIds)


# ---------------------------------------------------------------------------
# 12 -- empty references remain empty
# ---------------------------------------------------------------------------

class EmptyReferencesTests(unittest.TestCase):
    def test_fr_with_no_real_reference_anywhere_stays_empty_not_fabricated(self):
        fr = RequirementDto(id="FR-09", title="Symptom Corpus Data Management", description="", priority="Medium", source="s")
        uc = UseCaseDto(id="UC-11", title="Patient Deletes Account", actor="Patient", goal="", relatedRequirements=[])

        rows = _agent()._build_traceability([fr], [], [uc], [], [], [], [], [])

        row = rows[0]
        self.assertEqual(row.useCaseIds, [])
        self.assertEqual(row.moduleIds, [])
        self.assertEqual(row.entityIds, [])
        self.assertEqual(row.testCaseIds, [])
        self.assertEqual(row.coverageStatus, "uncovered")


# ---------------------------------------------------------------------------
# 13, 14 -- RequirementDto reverse references rebuilt from children; stale
# reverse references removed
# ---------------------------------------------------------------------------

class ReverseReferenceRebuildTests(unittest.TestCase):
    def test_reverse_use_case_and_module_ids_rebuilt_from_child_links(self):
        fr = RequirementDto(id="FR-02", title="Symptom Submission", description="", priority="High", source="s")
        uc = UseCaseDto(id="UC-03", title="Submit Symptoms", actor="Patient", goal="", relatedRequirements=["FR-02"])
        mod = ModuleDto(id="MOD-02", name="SymptomIntakeModule", responsibility="", relatedRequirements=["FR-02"])

        _agent()._rebuild_requirement_reverse_references([fr], [], [uc], [mod])

        self.assertEqual(fr.relatedUseCaseIds, ["UC-03"])
        self.assertEqual(fr.relatedModuleIds, ["MOD-02"])

    def test_stale_reverse_reference_is_replaced_not_preserved(self):
        """fr.relatedUseCaseIds starts out pointing at a use case that does
        NOT actually reference this FR (e.g. leftover from the requirements
        section's own independent, now-untrustworthy guess) -- the rebuild
        must overwrite it with the real child-derived answer, never merge
        with or preserve the stale value."""
        fr = RequirementDto(
            id="FR-02", title="Symptom Submission", description="", priority="High", source="s",
            relatedUseCaseIds=["UC-99"],  # stale / never real
        )
        uc_real = UseCaseDto(id="UC-03", title="Submit Symptoms", actor="Patient", goal="", relatedRequirements=["FR-02"])

        _agent()._rebuild_requirement_reverse_references([fr], [], [uc_real], [])

        self.assertEqual(fr.relatedUseCaseIds, ["UC-03"])
        self.assertNotIn("UC-99", fr.relatedUseCaseIds)


# ---------------------------------------------------------------------------
# 15 -- duplicate references collapse
# ---------------------------------------------------------------------------

class DedupeReferenceListTests(unittest.TestCase):
    def test_duplicate_ids_within_a_single_items_list_are_collapsed(self):
        uc = UseCaseDto(id="UC-03", title="Submit Symptoms", actor="Patient", goal="", relatedRequirements=["FR-02", "FR-02", "FR-03"])
        test = TestCaseDto(
            id="TC-05", title="t", type="Unit", expectedResult="r",
            relatedRequirements=["FR-02", "FR-02"], relatedUseCaseIds=["UC-03", "UC-03"],
        )

        _agent()._dedupe_reference_lists([uc], [], [], [], [], [test])

        self.assertEqual(uc.relatedRequirements, ["FR-02", "FR-03"])
        self.assertEqual(test.relatedRequirements, ["FR-02"])
        self.assertEqual(test.relatedUseCaseIds, ["UC-03"])


# ---------------------------------------------------------------------------
# 16 -- a removed FR is never remapped to the first available FR
# ---------------------------------------------------------------------------

class RemovedRequirementNeverRemappedTests(unittest.TestCase):
    def test_dangling_reference_to_a_removed_fr_is_dropped_not_remapped(self):
        requirement_ids = {"FR-01", "FR-02"}  # FR-99 no longer exists
        uc = UseCaseDto(id="UC-03", title="x", actor="Patient", goal="", relatedRequirements=["FR-99"])
        test = TestCaseDto(id="TC-01", title="t", type="Unit", expectedResult="r", relatedRequirements=["FR-99"])
        mod = ModuleDto(id="MOD-01", name="x", responsibility="", relatedRequirements=["FR-99"])

        _agent()._reconcile_requirement_references(requirement_ids, [uc], [], [mod], [test])

        # Never silently remapped to "FR-01" (the first sorted id) -- simply dropped.
        self.assertEqual(uc.relatedRequirements, [])
        self.assertEqual(test.relatedRequirements, [])
        self.assertEqual(mod.relatedRequirements, [])
        self.assertNotIn("FR-01", uc.relatedRequirements)


# ---------------------------------------------------------------------------
# 17, 18, 19, 20 -- full medical-triage fixture end to end
# ---------------------------------------------------------------------------

def _medical_request() -> SEDocumentationRequest:
    return SEDocumentationRequest()


def _medical_sections() -> dict:
    """Hand-built as if every dependent section's LLM call had already been
    generated WITH the RequirementsRegistry in its prompt -- i.e. this is
    what correct, registry-aware provider output looks like. Reproduces the
    exact ids named in the live defect report (UC-04, UC-05, UC-06, UC-07,
    UC-11, TC-03, TC-04, TC-20) with their CORRECT relatedRequirements, to
    prove the deterministic builder never reintroduces the reported bad
    links even though the ids exist and look superficially similar."""
    frs = [
        {"id": "FR-01", "title": "Patient Account Registration and Login", "description": "d", "priority": "High", "source": "s"},
        {"id": "FR-02", "title": "Symptom Description Submission", "description": "d", "priority": "High", "source": "s"},
        {"id": "FR-03", "title": "Send Symptom Text to FastAPI Triage Service", "description": "d", "priority": "High", "source": "s"},
        {"id": "FR-04", "title": "Symptom Urgency Classification", "description": "d", "priority": "High", "source": "s"},
        {"id": "FR-05", "title": "Specialist Recommendation", "description": "d", "priority": "High", "source": "s"},
        {"id": "FR-06", "title": "Display Triage Result", "description": "d", "priority": "High", "source": "s"},
        {"id": "FR-07", "title": "Symptom Submission History", "description": "d", "priority": "Medium", "source": "s"},
        {"id": "FR-09", "title": "Symptom Corpus Data Management", "description": "d", "priority": "Medium", "source": "s"},
    ]
    nfrs = [
        {"id": "NFR-01", "title": "Triage Response Time", "description": "d", "priority": "High", "source": "s", "measurableTarget": "Proposed acceptance target: under 5s."},
    ]

    use_cases = [
        {"id": "UC-01", "title": "Patient Registration", "actor": "Patient", "goal": "g", "relatedRequirements": ["FR-01"]},
        {"id": "UC-02", "title": "Patient Login", "actor": "Patient", "goal": "g", "relatedRequirements": ["FR-01"]},
        {"id": "UC-03", "title": "Submit Symptoms", "actor": "Patient", "goal": "g", "relatedRequirements": ["FR-02", "FR-03", "FR-04", "FR-05"]},
        {"id": "UC-04", "title": "View Triage History", "actor": "Patient", "goal": "g", "relatedRequirements": ["FR-07"]},
        {"id": "UC-05", "title": "Switch Interface Language", "actor": "Patient", "goal": "g", "relatedRequirements": []},
        {"id": "UC-06", "title": "Administrator Reviews Flagged Triage Cases", "actor": "Administrator", "goal": "g", "relatedRequirements": []},
        {"id": "UC-07", "title": "Administrator Manages User Accounts", "actor": "Administrator", "goal": "g", "relatedRequirements": []},
        {"id": "UC-08", "title": "Patient Logout", "actor": "Patient", "goal": "g", "relatedRequirements": ["FR-01"]},
        {"id": "UC-09", "title": "Specialist Reviews Recommendation", "actor": "Specialist", "goal": "g", "relatedRequirements": ["FR-05"]},
        {"id": "UC-10", "title": "System Sends Symptom Text to FastAPI", "actor": "Patient", "goal": "g", "relatedRequirements": ["FR-03", "FR-04", "FR-05"]},
        {"id": "UC-11", "title": "Patient Deletes Account", "actor": "Patient", "goal": "g", "relatedRequirements": []},
    ]
    edge_cases: list = []

    modules = [
        {"id": "MOD-01", "name": "AuthModule", "responsibility": "r", "relatedRequirements": ["FR-01"]},
        {"id": "MOD-04", "name": "ClassificationModule", "responsibility": "r", "relatedRequirements": ["FR-04"]},
        {"id": "MOD-05", "name": "RecommendationModule", "responsibility": "r", "relatedRequirements": ["FR-05"]},
        {"id": "MOD-06", "name": "HistoryModule", "responsibility": "r", "relatedRequirements": ["FR-07"]},
        {"id": "MOD-07", "name": "CorpusTrainingModule", "responsibility": "r", "relatedRequirements": ["FR-09"]},
    ]
    architecture = {"components": ["AuthModule: authenticates patients"], "communicationPaths": [], "explanation": "e"}

    entities = [
        {
            "entityId": "ENT-01", "name": "Patient", "purpose": "p",
            "fields": [{"name": "Id", "dataType": "int", "isPrimaryKey": True}, {"name": "FullName", "dataType": "string"}, {"name": "Email", "dataType": "string"}],
            "relatedRequirementIds": ["FR-01"],
        },
        {
            "entityId": "ENT-02", "name": "TriageSession", "purpose": "p",
            "fields": [
                {"name": "Id", "dataType": "int", "isPrimaryKey": True},
                {"name": "PatientId", "dataType": "int", "isForeignKey": True, "referencedEntity": "Patient", "referencedField": "Id"},
                {"name": "SymptomText", "dataType": "string"},
            ],
            "relatedRequirementIds": ["FR-02", "FR-03"],
        },
        {
            "entityId": "ENT-03", "name": "TriageResult", "purpose": "p",
            "fields": [
                {"name": "Id", "dataType": "int", "isPrimaryKey": True},
                {"name": "TriageSessionId", "dataType": "int", "isForeignKey": True, "referencedEntity": "TriageSession", "referencedField": "Id"},
                {"name": "UrgencyLevel", "dataType": "string"},
            ],
            "relatedRequirementIds": ["FR-04", "FR-05", "FR-06"],
        },
        {
            "entityId": "ENT-04", "name": "SymptomCorpusRecord", "purpose": "p",
            "fields": [{"name": "Id", "dataType": "int", "isPrimaryKey": True}, {"name": "SymptomText", "dataType": "string"}, {"name": "Label", "dataType": "string"}],
            "relatedRequirementIds": ["FR-09"],
        },
    ]
    entity_relationships = [
        {"fromEntity": "Patient", "toEntity": "TriageSession", "type": "one-to-many", "description": "d"},
        {"fromEntity": "TriageSession", "toEntity": "TriageResult", "type": "one-to-many", "description": "d"},
    ]

    ui_screens = [
        {"screenId": "UI-02", "name": "Symptom Entry", "purpose": "p", "relatedRequirements": ["FR-02"]},
        {"screenId": "UI-03", "name": "Triage History", "purpose": "p", "relatedRequirements": ["FR-07"]},
        {"screenId": "UI-04", "name": "Triage Result", "purpose": "p", "relatedRequirements": ["FR-06"]},
    ]
    api_points = [
        {
            "apiId": "API-01", "name": "Triage API", "method": "POST", "endpoint": "/triage",
            "purpose": "p", "requestSummary": "r", "responseSummary": "r", "relatedRequirements": ["FR-03"],
        },
    ]

    testing_plan = [
        {"id": "TC-01", "title": "Patient registration positive", "type": "Unit", "expectedResult": "r", "relatedRequirements": ["FR-01"], "relatedUseCaseIds": ["UC-01"]},
        {"id": "TC-02", "title": "Invalid login negative", "type": "Unit", "expectedResult": "r", "negativeCase": True, "relatedRequirements": ["FR-01"], "relatedUseCaseIds": ["UC-02"]},
        {"id": "TC-03", "title": "Patient login positive", "type": "Unit", "expectedResult": "r", "relatedRequirements": ["FR-01"], "relatedUseCaseIds": ["UC-02"]},
        {"id": "TC-04", "title": "Invalid login negative (bad password)", "type": "Unit", "expectedResult": "r", "negativeCase": True, "relatedRequirements": ["FR-01"], "relatedUseCaseIds": ["UC-02"]},
        {"id": "TC-20", "title": "Session expiration", "type": "Integration", "expectedResult": "r", "relatedRequirements": ["FR-01"], "relatedUseCaseIds": ["UC-08"]},
        {"id": "TC-05", "title": "Symptom submission positive", "type": "Integration", "expectedResult": "r", "relatedRequirements": ["FR-02"], "relatedUseCaseIds": ["UC-03"]},
        {"id": "TC-06", "title": "Triage integration request test", "type": "Integration", "expectedResult": "r", "relatedRequirements": ["FR-03"], "relatedUseCaseIds": ["UC-03"]},
        {"id": "TC-07", "title": "Urgency classification accuracy test", "type": "Integration", "expectedResult": "r", "relatedRequirements": ["FR-04"], "relatedUseCaseIds": ["UC-03"]},
        {"id": "TC-08", "title": "Specialist recommendation test", "type": "Integration", "expectedResult": "r", "relatedRequirements": ["FR-05"], "relatedUseCaseIds": ["UC-09"]},
        {"id": "TC-09", "title": "Triage history authorization test", "type": "Security", "expectedResult": "r", "relatedRequirements": ["FR-07"], "relatedUseCaseIds": ["UC-04"]},
        {"id": "TC-10", "title": "Corpus training data validation test", "type": "Unit", "expectedResult": "r", "relatedRequirements": ["FR-09"]},
    ]
    security = [{"category": "authentication", "requirement": "r"}]

    return {
        "requirements": {"functionalRequirements": frs, "nonFunctionalRequirements": nfrs},
        "useCases": {"useCases": use_cases, "edgeCases": edge_cases},
        "modulesArchitecture": {"systemModules": modules, "architecture": architecture},
        "database": {"databaseEntities": entities, "entityRelationships": entity_relationships},
        "uiApi": {"uiScreens": ui_screens, "apiIntegrationPoints": api_points},
        "testingSecurity": {"testingPlan": testing_plan, "securityAndPrivacy": security},
    }


class MedicalFixtureEndToEndTests(unittest.TestCase):
    def setUp(self):
        self.agent = _agent()
        self.facts = _facts()
        self.doc = self.agent._assemble_documentation(
            _medical_request(), self.facts, _medical_sections(), used_fallback=False,
        )
        self.rows_by_fr = {row.requirementId: row for row in self.doc.traceabilityMatrix}
        # systemModules and uiScreens are unconditionally renumbered by list
        # position (see _assign_canonical_ids), so look their final ids up
        # by the stable name instead of assuming the fixture's input id.
        self.module_id_by_name = {m.name: m.id for m in self.doc.systemModules}
        self.screen_id_by_name = {s.name: s.screenId for s in self.doc.uiScreens}

    def test_fr01_account_registration_login_minimum_mapping(self):
        row = self.rows_by_fr["FR-01"]
        self.assertEqual(set(row.useCaseIds), {"UC-01", "UC-02", "UC-08"})
        self.assertTrue(set(row.testCaseIds).issuperset({"TC-01", "TC-02", "TC-03", "TC-04", "TC-20"}))

    def test_fr02_symptom_submission_minimum_mapping(self):
        row = self.rows_by_fr["FR-02"]
        self.assertIn("UC-03", row.useCaseIds)
        self.assertIn("TC-05", row.testCaseIds)
        self.assertIn(self.screen_id_by_name["Symptom Entry"], row.screenIds)

    def test_fr03_fastapi_request_minimum_mapping(self):
        row = self.rows_by_fr["FR-03"]
        self.assertTrue({"UC-03", "UC-10"} & set(row.useCaseIds))
        self.assertIn("API-01", row.apiIds)
        self.assertIn("TC-06", row.testCaseIds)

    def test_fr04_urgency_classification_minimum_mapping(self):
        row = self.rows_by_fr["FR-04"]
        self.assertTrue({"UC-03", "UC-10"} & set(row.useCaseIds))
        self.assertIn(self.module_id_by_name["ClassificationModule"], row.moduleIds)
        self.assertIn("ENT-03", row.entityIds)
        self.assertIn("TC-07", row.testCaseIds)

    def test_fr05_specialist_recommendation_minimum_mapping(self):
        row = self.rows_by_fr["FR-05"]
        self.assertTrue({"UC-03", "UC-09", "UC-10"} & set(row.useCaseIds))
        self.assertIn(self.module_id_by_name["RecommendationModule"], row.moduleIds)
        self.assertIn("TC-08", row.testCaseIds)

    def test_fr07_symptom_history_minimum_mapping(self):
        row = self.rows_by_fr["FR-07"]
        self.assertIn("UC-04", row.useCaseIds)
        self.assertIn(self.screen_id_by_name["Triage History"], row.screenIds)
        self.assertIn("TC-09", row.testCaseIds)

    def test_fr09_corpus_data_management_minimum_mapping_never_delete_account(self):
        row = self.rows_by_fr["FR-09"]
        self.assertIn(self.module_id_by_name["CorpusTrainingModule"], row.moduleIds)
        self.assertIn("ENT-04", row.entityIds)
        self.assertIn("TC-10", row.testCaseIds)
        self.assertNotIn("UC-11", row.useCaseIds)

    def test_matrix_never_contains_the_reported_corrupted_links(self):
        self.assertNotIn("TC-03", self.rows_by_fr["FR-02"].testCaseIds)
        self.assertNotIn("TC-04", self.rows_by_fr["FR-02"].testCaseIds)
        self.assertNotIn("TC-20", self.rows_by_fr["FR-02"].testCaseIds)
        self.assertNotIn("UC-04", self.rows_by_fr["FR-04"].useCaseIds)
        self.assertNotIn("UC-05", self.rows_by_fr["FR-05"].useCaseIds)
        self.assertNotIn("UC-06", self.rows_by_fr["FR-06"].useCaseIds)
        self.assertNotIn("UC-07", self.rows_by_fr["FR-07"].useCaseIds)
        self.assertNotIn("UC-11", self.rows_by_fr["FR-09"].useCaseIds)

    def test_full_candidate_still_passes_structural_validation(self):
        candidate = self.doc.model_dump()
        SEDocumentationCandidateSchema.model_validate(candidate)

    def test_no_live_provider_call_was_made(self):
        # Purely a documentation assertion: this whole test class only ever
        # calls _assemble_documentation directly with hand-built dicts --
        # no ProviderChain / LLM call is reachable from that code path.
        self.assertIsNotNone(self.doc)


if __name__ == "__main__":
    unittest.main()
